- name: Configure agent Server
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server=.*$'
    line: "Server={{ zabbix_server_yggdrasil_IP }}"
    backrefs: yes

- name: Configure agent ServerActive
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive=.*$'
    line: "ServerActive={{ zabbix_server_yggdrasil_IP }}"
    backrefs: yes

- name: Configure agent Hostname
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Hostname=.*$'
    line: "Hostname=agent{{ zabbix_agent_hostName }}"
    backrefs: yes
  notify: restart zabbix-agent