# ======================================== PLAYBOOK BEHAVIOR
drop_vm: true
generate_ssh_key: true
path_to_public_key: ".ssh/cluster_key.pub"
path_to_private_key: ".ssh/cluster_key"
reconfigure_yggdrasil: true

# ======================================== HOST'S CONF
server_ip: 
server_username: 
server_ssh_port: 
server_path_to_ssh_pub_key: 
server_path_to_ssh_private_key: 
server_password: 
server_rootpassword: ""

# ======================================== YGGDRASIL'S CONF
server_yggdrasil_port: 
server_yggdrasil_interface: 0.0.0.0
yggdrasil_package: yggdrasil-0.5.7-amd64.deb
yggdrasil_public_keys:

# ======================================== ZABBIX'S CONF
zabbix_package: zabbix-release_7.0-2+debian12_all.deb
php_version: 8.3