---
- name: Install gnupg
  ansible.builtin.apt:
    name: gnupg
    state: present
- name: Add Sury PHP repository key (Debian)
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
  when: ansible_facts['distribution'] == "Debian"

- name: Add Sury repository to sources list (Debian)
  ansible.builtin.apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_facts['distribution_release'] }} main"
    state: present
  when: ansible_facts['distribution'] == "Debian"

- name: Update all packages after adding Sury repository (Debian)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_facts['distribution'] == "Debian"

- name: Install php{{ php_version }}
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
    state: present

