- name: install and configure nftables and fail2ban
  hosts: server
  become: true
  become_method: sudo
  vars_files:
    - group_vars/secret.yml
  tasks:

    - name: Check if nftables is already installed
      shell: dpkg -l | grep nftables
      register: nftables_installed
      ignore_errors: yes

    - name: Check if fail2ban is already installed
      shell: dpkg -l | grep fail2ban
      register: fail2ban_installed
      ignore_errors: yes
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: nftables_installed.stdout == "" or fail2ban_installed.stdout == ""
    
    - name: Install nftables
      include_role:
        name: install_nftables
      when: nftables_installed.stdout == ""
    
    - name: Configure nftables
      include_role:
        name: configure_nftables
      when: reconfigure_nftables == true && nftables_installed.stdout != ""
    
    - name: Install fail2ban
      include_role:
        name: install_fail2ban
      when: fail2ban_installed.stdout == ""

    - name: Configure fail2ban
      include_role:
        name: configure_fail2ban
      when: reconfigure_fail2ban == true && fail2ban_installed.stdout != ""