- name: install zabbix on server
  hosts: localhost
  become: true
  become_method: sudo
  vars_files:
    - group_vars/secret.yml
  tasks:

    - name: Check if zabbix is already installed
      shell: dpkg -l | grep zabbix
      register: zabbix_installed
      ignore_errors: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: zabbix_installed.stdout == ""
    
    - name: Install zabbix
      include_role:
        name: install_zabbix_agent2
      when: zabbix_installed.stdout == ""
    
    - name: Configure zabbix agent
      include_role:
        name: configure_zabbix_agent2
      # when: reconfigure_zabbix_agent == "true"
  