---
- name: Download Zabbix repository package
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/{{ zabbix_package }}"
    dest: "/tmp/{{ zabbix_package }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0664'

- name: Install zabbix-release package
  ansible.builtin.apt:
    deb: "/tmp/{{ zabbix_package }}"
    state: present
    update_cache: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Zabbix server, frontend, agent
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - zabbix-server-mysql
    - zabbix-frontend-php
    - zabbix-apache-conf
    - zabbix-sql-scripts
    - zabbix-agent2
    - zabbix-agent2-plugin-*
    - gzip
  notify: restart zabbix-agent

- name: Ensure post_max_size is set to 16M
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: '^post_max_size\s*='
    line: 'post_max_size = 16M'
    state: present

- name: Ensure max_execution_time is set to 300
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: '^max_execution_time\s*='
    line: 'max_execution_time = 300'
    state: present

- name: Ensure max_input_time is set to 300
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: '^max_input_time\s*='
    line: 'max_input_time = 300'
    state: present

- name: Restart php"{{ php_version }}"-fpm to apply changes
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: Restart Apache to apply changes
  service:
    name: apache2
    state: restarted

- name: Install locales package
  apt:
    name: locales
    state: present